on: 
  workflow_dispatch:
    inputs:
      pullRequestNumber:
        type: string
        required: true
        default: '0'
      externalId:
        type: string
        required: true
        default: '0'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      pullRequestNumber: ${{ inputs.pullRequestNumber }}
      externalId: ${{ inputs.externalId }}
    permissions:
      id-token: write
      contents: read
      checks: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'awslabs/generative-ai-cdk-constructs'
      - name: Get the PR and test mergeability
        if: fromJSON(inputs.pullRequestNumber) > 0
        run: |-
          gh pr checkout ${{ inputs.pullRequestNumber }};
          git merge `gh pr view ${{ inputs.pullRequestNumber }} --json baseRefName | jq -r '.baseRefName'`
          echo "::group::Git Differences"
          git diff `gh pr view ${{ inputs.pullRequestNumber }} --json baseRefName | jq -r '.baseRefName'`..HEAD
          echo "::endgroup::"
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - run: |-
          npm install -g aws-cdk
          npx projen install
          npx projen default
          npx projen pre-compile
          npx projen compile
          npx projen post-compile
          npx projen package-all
          ls -lR ./dist/

