on: 
  workflow_dispatch:
    inputs:
      pullRequestNumber:
        type: string
        required: true
        default: '2'
      checkRunId:
        type: string
        required: true
        default: '25237483792'
jobs:
  tester:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      id-token: write
      contents: read
      checks: write
      pull-requests: read
    steps:
      - name: Echo the event
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT
      - name: Inputs
        run: |
          cat << OBJECT
          ${{ toJson(inputs) }}
          OBJECT
      - name: GitHub CLI version
        run: gh --version
      - name: stuff
        run: echo ${{github.event.repository.name}} ${{github.event.repository.owner.login}} ${{inputs.pullRequestNumber}} ${{inputs.checkRunId}}
      - name: Run GitHub API GraphQL
        id: graphql
        run: |
          echo checkRun=`gh api graphql \
              --raw-field repositoryName="${{github.event.repository.name}}" \
              --raw-field repositoryOwner="${{github.event.repository.owner.login}}" \
              --field pullRequestNumber="${{inputs.pullRequestNumber}}" \
              --field query='query($repositoryName: String!, $repositoryOwner: String!, $pullRequestNumber: Int!){
                repository(followRenames: true, name: $repositoryName, owner: $repositoryOwner) {
                  pullRequest(number: $pullRequestNumber) {
                    state
                    reviewDecision
                    mergeable
                    statusCheckRollup {
                      contexts(first: 100) {
                        checkRunCount
                        nodes {
                          ... on CheckRun {
                            id
                            isRequired(pullRequestNumber: $pullRequestNumber)
                            name
                            status
                            databaseId
                            externalId
                            conclusion
                            summary
                            text
                            title
                          }
                        }
                      }
                    }
                  }
                }
              }' | jq -c '.data.repository.pullRequest | select (.state == "OPEN") | select (.reviewDecision == "APPROVED") | select (.mergeable == "MERGEABLE") | .statusCheckRollup.contexts.nodes[] | select (.databaseId == ${{ inputs.checkRunId }}) | .'` >> "$GITHUB_OUTPUT"
      - name: Debug the outputs from the GraphQL output
        run: |
          echo "4"
          cat << OBJECT
          ${{ steps.graphql.outputs.checkRun }}
          OBJECT
          echo "5"
          echo '${{ steps.graphql.outputs.checkRun }}'
      - name: If the check run status is completed
        if: ( ${{ steps.graphql.outputs.checkRun.status }} == 'COMPLETED')
        run: echo "COMPLETED"
      - name: If the status is not completed
        if: ( ${{ steps.graphql.outputs.checkRun.status }} != 'COMPLETED')
        run: echo "NOT COMPLETED ${{ steps.graphql.outputs.checkRun.status }}"
      - name: ExternalId
        run: echo "This is the externalId ${{ steps.graphql.outputs.checkRun.externalId }}"    
