on: 
  workflow_dispatch:
    inputs:
      externalId:
        type: string
        required: true
        default: ''
jobs:
  manual:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - name: Echo the event
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT
      - name: Inputs
        run: |
          cat << OBJECT
          ${{ toJson(inputs) }}
          OBJECT
      - name: GitHub CLI version
        run: gh --version
      - name: Run GitHub API GraphQL
        run: gh api graphql --field query='query{meta{hookIpAddresses}}' | jq -c '.data.meta.hookIpAddresses'
